//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAI_Zilya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluations
    {
        public int ID_Student { get; set; }
        public Nullable<System.DateTime> Date_Exam1 { get; set; }
        public Nullable<int> ID_Subjects1 { get; set; }
        public Nullable<int> Evaluations1 { get; set; }
        public Nullable<System.DateTime> Date_Exam2 { get; set; }
        public Nullable<int> ID_Subjects2 { get; set; }
        public Nullable<int> Evaluations2 { get; set; }
        public Nullable<double> Average_Score { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Subjects Subjects1 { get; set; }
    }
}
