//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAI_Zilya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID_Student { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Parents { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Pasport_num { get; set; }
        public Nullable<int> Credit_Card_Number { get; set; }
        public Nullable<System.DateTime> Date_Of_Receipt { get; set; }
        public string Group { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> ID_Specialties { get; set; }
        public Nullable<bool> Full_Time_Education { get; set; }
    
        public virtual Evaluations Evaluations { get; set; }
        public virtual Specialties Specialties { get; set; }
    }
}
